// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpxqcjooahjbptcxepif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNweHFjam9vYWhqYnB0Y3hlcGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzk0NjIsImV4cCI6MjA2OTc1NTQ2Mn0.Bp22pihQNqJVRoVbWgX4StHXrK01a5IPu7dVpsKJay4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});